### ISSUE TITLE
How to achieve 98.91% of ImageNet Accuracy 

### ISSUE THREAD

**Issue by ahatamiz** [taesiri/ZoomIsAllYouNeed#1]
Hi authors! 

Congratulations for this amazing work. Very interesting indeed. I was reading the paper and the following caught my attention: 

" ...we find that proper framing of the input image can lead to the correct classification of 98.91% of [ImageNet](https://www.image-net.org/) images."

I assume **98.91%** denote **Top-1 accuracy**. However, according to a [study](https://datasets-benchmarks-proceedings.neurips.cc/paper/2021/file/f2217062e9a397a1dca429e7d70bc6ca-Paper-round1.pdf) from MIT, at least 6% of ImageNet validation set labels are incorrect. I wonder how the authors may justify this discrepancy.

**Comment by taesiri** [comment]
Hello @ahatamiz 

Thank you for your interest in our work.

Yes, we are aware of the labeling issues with the original ImageNet and its OOD validation sets. To reduce labeling noise, we used [ImageNet-ReaL](https://arxiv.org/abs/2006.07159) labels and combined them with the original labels from ImageNet to minimize the noise (IN+ReaL in Table 1). It should be highlighted that a classifier is given 324 different crops of the original query, and we check whether the classifier's prediction matches any of the GT labels (following the setup from ImageNet-ReaL). 

It is worth highlighting that, sometimes the labeling issue is about a different but similar animal (`black stork` vs `white stork` in the paper you've mentioned), or multiple objects (`keyboard` vs `monitor`). In such cases, one of the crops will help the classifier to the same label as the GT.

**Comment by ahatamiz** [comment]
Thanks @taesiri for providing the comprehensive answer. I am also more in favor of evaluation of multiple datasets. But my attention was drawn to this paper, since we have been almost stuck at improving the ImageNet performance since a couple of years for now -- best model is currently around 92%. 

It would also be great to further improve the performance with only a single crop as well.
